# Site settings
title: Ha Eun Jang # site title
description: >- # site description
  Researcher in HCI and AI exploring affective computing, 
  AI-mediated communication, and culturally sensitive systems.
lang: en-US # default lang
timezone: Asia/Seoul # set your timezone
image: /assets/img/main_img.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/ha-eun-jang/ha-eun-jang.github.io.git # site repo [optional]
mode: "light" # default theme "dark" | "light"

# Profile settings
author:
  name: Ha Eun Jang # author name
  bio: | # tell to the world
    Hello, I'm a second-year Master's student at  <a href="https://www.uicinnovation.yonsei.ac.kr/" target="_blank" rel="noopener">Underwood International College</a>,
    Yonsei University, working with <a href="https://jyskwon.github.io/" target="_blank" rel="noopener">Prof. Jean Young Song</a> at the <a href="https://www.diag.kr/" target="_blank" rel="noopener">DIAG Lab</a>. 
    
    My research lies at the intersection of Human-Computer Interaction (HCI) and AI, 
    with a focus on understanding how AI can serve as a human-centered tool that supports 
    self-exploration and communication in complex social and cultural contexts.
    Before joining DIAG Lab, I worked as a marketer and designer, which shaped my interdisciplinary 
    perspective on human behavior, psychology, and the design of AI systems. 
    I am always open to exploring new domains and emerging research questions.
  username: ha-eun-jang # general username
  github: ha-eun-jang # github username
  twitter:  # twitter username
  facebook:  # facebook username
  email: j.haeun@yonsei.ac.kr # email adress
  avatar: /assets/img/profile.jpg # change with your own avatar
  position: "Master's Student @ Yonsei University" # job position

# URL settings
url: "https://klise.now.sh" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
